version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./db-variables.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muzz-backend-challenge
    restart: unless-stopped
    ports:
      - "8089:8089"
    env_file:
      - ./db-variables.env
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
